package com.visiondigitallab.visionone.lead.internal;

import com.visiondigitallab.visionone.auth.CurrentUser;
import com.visiondigitallab.visionone.common.NotFoundException;
import com.visiondigitallab.visionone.eventing.api.DomainEventPublisher;
import com.visiondigitallab.visionone.eventing.api.EventType;
import com.visiondigitallab.visionone.lead.api.LeadWriteRequests;
import com.visiondigitallab.visionone.lead.domain.Lead;
import com.visiondigitallab.visionone.lead.domain.LeadStatus;
import com.visiondigitallab.visionone.lead.domain.LeadStatusHistory;
import com.visiondigitallab.visionone.lead.domain.ServiceInterest;
import com.visiondigitallab.visionone.lead.repository.LeadRepository;
import com.visiondigitallab.visionone.lead.repository.LeadStatusHistoryRepository;
import com.visiondigitallab.visionone.tenant.api.OrganizationContext;
import java.time.Instant;
import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Vision Admin's write path for the pipeline.
 *
 * <p>Every transition appends history and publishes through the outbox in the same transaction, so
 * the funnel, the audit trail and the event stream can never disagree with the lead's own status.
 */
@Service
public class LeadAdminService {

    private static final String AGGREGATE = "Lead";

    private final LeadRepository leads;
    private final LeadStatusHistoryRepository history;
    private final DomainEventPublisher events;
    private final CurrentUser currentUser;
    private final JdbcClient jdbc;

    public LeadAdminService(
            LeadRepository leads,
            LeadStatusHistoryRepository history,
            DomainEventPublisher events,
            CurrentUser currentUser,
            JdbcClient jdbc) {
        this.leads = leads;
        this.history = history;
        this.events = events;
        this.currentUser = currentUser;
        this.jdbc = jdbc;
    }

    @Transactional
    public UUID create(OrganizationContext context, LeadWriteRequests.CreateLead request) {
        requireOwnChannel(context.organizationId(), request.channelSourceId());

        Lead lead = new Lead(
                UUID.randomUUID(),
                context.organizationId(),
                request.channelSourceId(),
                request.displayName(),
                parseInterest(request.serviceInterest()));
        lead.correctDetails(request.displayName(), parseInterest(request.serviceInterest()), request.campaignId());
        if (request.ownerMembershipId() != null) {
            lead.reassign(request.ownerMembershipId());
        }
        leads.save(lead);
        // The reference is generated by the database sequence, so read it back before publishing.
        leads.flush();

        appendHistory(context, lead.getId(), null, LeadStatus.NEW, null);
        events.publish(
                EventType.LEAD_CREATED,
                context.organizationId(),
                AGGREGATE,
                lead.getId(),
                new LeadCreatedPayload(
                        lead.getId(),
                        lead.getReference(),
                        lead.getChannelSourceId(),
                        lead.getCampaignId(),
                        lead.getServiceInterest().name(),
                        lead.getCreatedAt().toString()));
        return lead.getId();
    }

    @Transactional
    public void update(OrganizationContext context, UUID leadId, LeadWriteRequests.UpdateLead request) {
        Lead lead = require(context, leadId);
        lead.correctDetails(request.displayName(), parseInterest(request.serviceInterest()), request.campaignId());
        if (request.ownerMembershipId() != null) {
            lead.reassign(request.ownerMembershipId());
        }
        leads.save(lead);
    }

    /**
     * Moves a lead and records why.
     *
     * <p>A no-op transition is accepted and does nothing rather than erroring: a double-clicked
     * status control should not be an error the client sees.
     */
    @Transactional
    public void transition(
            OrganizationContext context, UUID leadId, LeadWriteRequests.TransitionLead request) {
        Lead lead = require(context, leadId);
        LeadStatus next = parseStatus(request.toStatus());
        if (lead.getStatus() == next) {
            return;
        }

        Instant when = Instant.now();
        LeadStatus previous = lead.transitionTo(next, when);
        leads.save(lead);
        appendHistory(context, leadId, previous, next, request.reason());

        events.publish(
                EventType.LEAD_STATUS_CHANGED,
                context.organizationId(),
                AGGREGATE,
                leadId,
                new LeadStatusChangedPayload(
                        leadId,
                        lead.getReference(),
                        previous.name(),
                        next.name(),
                        when.toString(),
                        currentUser.displayName(),
                        request.reason()));
    }

    private void appendHistory(
            OrganizationContext context, UUID leadId, LeadStatus from, LeadStatus to, String reason) {
        history.save(new LeadStatusHistory(
                UUID.randomUUID(),
                context.organizationId(),
                leadId,
                from,
                to,
                currentUser.displayName(),
                reason));
    }

    private Lead require(OrganizationContext context, UUID leadId) {
        return leads
                .findByIdAndOrganizationId(leadId, context.organizationId())
                .orElseThrow(() -> new NotFoundException("Lead", leadId));
    }

    /** A channel id belonging to another organization must not be writable here. */
    private void requireOwnChannel(UUID organizationId, UUID channelSourceId) {
        Long found = jdbc.sql("select count(*) from channel_source "
                        + "where id = :id and organization_id = :orgId and active")
                .param("id", channelSourceId)
                .param("orgId", organizationId)
                .query(Long.class)
                .single();
        if (found == null || found == 0L) {
            throw new NotFoundException("ChannelSource", channelSourceId);
        }
    }

    private static ServiceInterest parseInterest(String raw) {
        try {
            return ServiceInterest.valueOf(raw);
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("Unknown service interest: " + raw);
        }
    }

    private static LeadStatus parseStatus(String raw) {
        try {
            return LeadStatus.valueOf(raw);
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("Unknown lead status: " + raw);
        }
    }

    public record LeadCreatedPayload(
            UUID leadId, String reference, UUID channelSourceId, UUID campaignId,
            String serviceInterest, String createdAt) {}

    public record LeadStatusChangedPayload(
            UUID leadId, String reference, String fromStatus, String toStatus,
            String changedAt, String changedBy, String reason) {}
}
